// Code generated by protoc-gen-psrpc v0.2.9, DO NOT EDIT.
// source: rpc/egress.proto

package rpc

import context "context"
import psrpc "github.com/livekit/psrpc"
import version "github.com/livekit/psrpc/version"
import livekit1 "github.com/livekit/protocol/livekit"

var _ = version.PsrpcVersion_0_2_9

// ===============================
// EgressInternal Client Interface
// ===============================

type EgressInternalClient interface {
	StartEgress(ctx context.Context, topic string, req *StartEgressRequest, opts ...psrpc.RequestOption) (*livekit1.EgressInfo, error)

	ListActiveEgress(ctx context.Context, req *ListActiveEgressRequest, opts ...psrpc.RequestOption) (<-chan *psrpc.Response[*ListActiveEgressResponse], error)
}

// ===================================
// EgressInternal ServerImpl Interface
// ===================================

type EgressInternalServerImpl interface {
	StartEgress(context.Context, *StartEgressRequest) (*livekit1.EgressInfo, error)
	StartEgressAffinity(*StartEgressRequest) float32

	ListActiveEgress(context.Context, *ListActiveEgressRequest) (*ListActiveEgressResponse, error)
}

// ===============================
// EgressInternal Server Interface
// ===============================

type EgressInternalServer interface {
	RegisterStartEgressTopic(topic string) error
	DeregisterStartEgressTopic(topic string)

	// Close and wait for pending RPCs to complete
	Shutdown()

	// Close immediately, without waiting for pending RPCs
	Kill()
}

// =====================
// EgressInternal Client
// =====================

type egressInternalClient struct {
	client *psrpc.RPCClient
}

// NewEgressInternalClient creates a psrpc client that implements the EgressInternalClient interface.
func NewEgressInternalClient(clientID string, bus psrpc.MessageBus, opts ...psrpc.ClientOption) (EgressInternalClient, error) {
	rpcClient, err := psrpc.NewRPCClient("EgressInternal", clientID, bus, opts...)
	if err != nil {
		return nil, err
	}

	return &egressInternalClient{
		client: rpcClient,
	}, nil
}

func (c *egressInternalClient) StartEgress(ctx context.Context, topic string, req *StartEgressRequest, opts ...psrpc.RequestOption) (*livekit1.EgressInfo, error) {
	return psrpc.RequestSingle[*livekit1.EgressInfo](ctx, c.client, "StartEgress", []string{topic}, true, req, opts...)
}

func (c *egressInternalClient) ListActiveEgress(ctx context.Context, req *ListActiveEgressRequest, opts ...psrpc.RequestOption) (<-chan *psrpc.Response[*ListActiveEgressResponse], error) {
	return psrpc.RequestMulti[*ListActiveEgressResponse](ctx, c.client, "ListActiveEgress", nil, req, opts...)
}

// =====================
// EgressInternal Server
// =====================

type egressInternalServer struct {
	svc EgressInternalServerImpl
	rpc *psrpc.RPCServer
}

// NewEgressInternalServer builds a RPCServer that will route requests
// to the corresponding method in the provided svc implementation.
func NewEgressInternalServer(serverID string, svc EgressInternalServerImpl, bus psrpc.MessageBus, opts ...psrpc.ServerOption) (EgressInternalServer, error) {
	s := psrpc.NewRPCServer("EgressInternal", serverID, bus, opts...)

	var err error
	err = psrpc.RegisterHandler(s, "ListActiveEgress", nil, svc.ListActiveEgress, nil, false)
	if err != nil {
		s.Close(false)
		return nil, err
	}

	return &egressInternalServer{
		svc: svc,
		rpc: s,
	}, nil
}

func (s *egressInternalServer) RegisterStartEgressTopic(topic string) error {
	return psrpc.RegisterHandler(s.rpc, "StartEgress", []string{topic}, s.svc.StartEgress, s.svc.StartEgressAffinity, true)
}

func (s *egressInternalServer) DeregisterStartEgressTopic(topic string) {
	s.rpc.DeregisterHandler("StartEgress", []string{topic})
}

func (s *egressInternalServer) Shutdown() {
	s.rpc.Close(false)
}

func (s *egressInternalServer) Kill() {
	s.rpc.Close(true)
}

// ==============================
// EgressHandler Client Interface
// ==============================

type EgressHandlerClient interface {
	UpdateStream(ctx context.Context, topic string, req *livekit1.UpdateStreamRequest, opts ...psrpc.RequestOption) (*livekit1.EgressInfo, error)

	StopEgress(ctx context.Context, topic string, req *livekit1.StopEgressRequest, opts ...psrpc.RequestOption) (*livekit1.EgressInfo, error)
}

// ==================================
// EgressHandler ServerImpl Interface
// ==================================

type EgressHandlerServerImpl interface {
	UpdateStream(context.Context, *livekit1.UpdateStreamRequest) (*livekit1.EgressInfo, error)

	StopEgress(context.Context, *livekit1.StopEgressRequest) (*livekit1.EgressInfo, error)
}

// ==============================
// EgressHandler Server Interface
// ==============================

type EgressHandlerServer interface {
	RegisterUpdateStreamTopic(topic string) error
	DeregisterUpdateStreamTopic(topic string)
	RegisterStopEgressTopic(topic string) error
	DeregisterStopEgressTopic(topic string)

	// Close and wait for pending RPCs to complete
	Shutdown()

	// Close immediately, without waiting for pending RPCs
	Kill()
}

// ====================
// EgressHandler Client
// ====================

type egressHandlerClient struct {
	client *psrpc.RPCClient
}

// NewEgressHandlerClient creates a psrpc client that implements the EgressHandlerClient interface.
func NewEgressHandlerClient(clientID string, bus psrpc.MessageBus, opts ...psrpc.ClientOption) (EgressHandlerClient, error) {
	rpcClient, err := psrpc.NewRPCClient("EgressHandler", clientID, bus, opts...)
	if err != nil {
		return nil, err
	}

	return &egressHandlerClient{
		client: rpcClient,
	}, nil
}

func (c *egressHandlerClient) UpdateStream(ctx context.Context, topic string, req *livekit1.UpdateStreamRequest, opts ...psrpc.RequestOption) (*livekit1.EgressInfo, error) {
	return psrpc.RequestSingle[*livekit1.EgressInfo](ctx, c.client, "UpdateStream", []string{topic}, true, req, opts...)
}

func (c *egressHandlerClient) StopEgress(ctx context.Context, topic string, req *livekit1.StopEgressRequest, opts ...psrpc.RequestOption) (*livekit1.EgressInfo, error) {
	return psrpc.RequestSingle[*livekit1.EgressInfo](ctx, c.client, "StopEgress", []string{topic}, true, req, opts...)
}

// ====================
// EgressHandler Server
// ====================

type egressHandlerServer struct {
	svc EgressHandlerServerImpl
	rpc *psrpc.RPCServer
}

// NewEgressHandlerServer builds a RPCServer that will route requests
// to the corresponding method in the provided svc implementation.
func NewEgressHandlerServer(serverID string, svc EgressHandlerServerImpl, bus psrpc.MessageBus, opts ...psrpc.ServerOption) (EgressHandlerServer, error) {
	s := psrpc.NewRPCServer("EgressHandler", serverID, bus, opts...)

	return &egressHandlerServer{
		svc: svc,
		rpc: s,
	}, nil
}

func (s *egressHandlerServer) RegisterUpdateStreamTopic(topic string) error {
	return psrpc.RegisterHandler(s.rpc, "UpdateStream", []string{topic}, s.svc.UpdateStream, nil, true)
}

func (s *egressHandlerServer) DeregisterUpdateStreamTopic(topic string) {
	s.rpc.DeregisterHandler("UpdateStream", []string{topic})
}

func (s *egressHandlerServer) RegisterStopEgressTopic(topic string) error {
	return psrpc.RegisterHandler(s.rpc, "StopEgress", []string{topic}, s.svc.StopEgress, nil, true)
}

func (s *egressHandlerServer) DeregisterStopEgressTopic(topic string) {
	s.rpc.DeregisterHandler("StopEgress", []string{topic})
}

func (s *egressHandlerServer) Shutdown() {
	s.rpc.Close(false)
}

func (s *egressHandlerServer) Kill() {
	s.rpc.Close(true)
}

var psrpcFileDescriptor0 = []byte{
	// 493 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xdf, 0x6e, 0xda, 0x30,
	0x18, 0xc5, 0xe7, 0x31, 0x02, 0xf9, 0x28, 0xac, 0xf2, 0x3a, 0xe1, 0xa6, 0xad, 0x84, 0xb2, 0x5d,
	0xa0, 0x6a, 0x0b, 0x12, 0xbd, 0xda, 0xe5, 0x3a, 0x21, 0x15, 0xa9, 0xda, 0xa6, 0xb0, 0xaa, 0xd2,
	0x6e, 0x50, 0x70, 0x3c, 0x66, 0x91, 0xc4, 0x9e, 0x6d, 0xe0, 0x19, 0xfa, 0x18, 0x7b, 0x83, 0xa9,
	0xef, 0xb2, 0xf7, 0x99, 0x70, 0x20, 0x0d, 0x54, 0x4c, 0xbd, 0x42, 0x3e, 0xe7, 0x7c, 0x3f, 0x8e,
	0xff, 0x04, 0x0e, 0x95, 0xa4, 0x3d, 0x36, 0x55, 0x4c, 0xeb, 0x40, 0x2a, 0x61, 0x04, 0xae, 0x28,
	0x49, 0xbd, 0xa6, 0x90, 0x86, 0x8b, 0x6c, 0xad, 0x79, 0x47, 0x09, 0x5f, 0xb0, 0x19, 0x37, 0xe3,
	0x72, 0xd2, 0xff, 0x5b, 0x01, 0x3c, 0x32, 0x91, 0x32, 0x03, 0xab, 0x86, 0xec, 0xd7, 0x9c, 0x69,
	0x83, 0x4f, 0xc0, 0xcd, 0x63, 0x63, 0x1e, 0x13, 0xd4, 0x41, 0x5d, 0x37, 0xac, 0xe7, 0xc2, 0x30,
	0xc6, 0xd7, 0xd0, 0x52, 0x42, 0xa4, 0x63, 0x2a, 0x52, 0x29, 0x34, 0x37, 0x8c, 0x54, 0x3b, 0xa8,
	0xdb, 0xe8, 0xbf, 0x09, 0xd6, 0x7f, 0x11, 0x84, 0x42, 0xa4, 0x9f, 0x36, 0xee, 0x16, 0xf9, 0xea,
	0x59, 0xd8, 0x54, 0x65, 0x17, 0xbf, 0x87, 0xca, 0x92, 0x4d, 0x48, 0xc3, 0x22, 0x8e, 0x0b, 0xc4,
	0x2d, 0x9b, 0xec, 0x0e, 0xae, 0x72, 0xf8, 0x33, 0x34, 0x64, 0xa4, 0x0c, 0xa7, 0x5c, 0x46, 0x99,
	0x21, 0x07, 0x76, 0xec, 0xbc, 0x18, 0xfb, 0xfa, 0xe0, 0xed, 0x2d, 0x50, 0x06, 0xe0, 0x2f, 0xf0,
	0xd2, 0xa8, 0x88, 0xce, 0x4a, 0xbb, 0x71, 0x2c, 0xf3, 0x6d, 0xc1, 0xfc, 0xb6, 0xf2, 0xf7, 0xd2,
	0x5a, 0x66, 0xcb, 0xc6, 0x17, 0x50, 0xb5, 0x0a, 0xa9, 0x59, 0xcc, 0xc9, 0x36, 0x66, 0x77, 0x3a,
	0xcf, 0xe2, 0x36, 0xd4, 0xec, 0x91, 0xf2, 0x98, 0x54, 0xec, 0x69, 0x3b, 0xab, 0xe5, 0x30, 0xc6,
	0x47, 0x50, 0x35, 0x62, 0xc6, 0x32, 0x52, 0xb7, 0x72, 0xbe, 0xc0, 0xaf, 0xc1, 0x59, 0xea, 0xf1,
	0x5c, 0x25, 0xc4, 0xcd, 0xe5, 0xa5, 0xbe, 0x51, 0xc9, 0xa5, 0x0b, 0x35, 0x95, 0x93, 0xfd, 0x63,
	0x68, 0x5f, 0x73, 0x6d, 0x3e, 0x52, 0xc3, 0x17, 0xdb, 0x95, 0xfd, 0x0f, 0x40, 0x1e, 0x5b, 0x5a,
	0x8a, 0x4c, 0x33, 0x7c, 0x06, 0x50, 0xdc, 0xbb, 0x26, 0xa8, 0x53, 0xe9, 0xba, 0xa1, 0xbb, 0xb9,
	0x78, 0xdd, 0xff, 0x83, 0xa0, 0x95, 0x4f, 0x0c, 0x33, 0xc3, 0x54, 0x16, 0x25, 0x78, 0x00, 0x8d,
	0xd2, 0xfb, 0xc1, 0xed, 0x40, 0x49, 0x1a, 0x3c, 0x7e, 0x51, 0xde, 0xab, 0xe2, 0x1c, 0x36, 0x80,
	0x1f, 0xc2, 0xaf, 0xdf, 0xdf, 0xa1, 0x17, 0x04, 0x75, 0x11, 0xbe, 0x85, 0xc3, 0xdd, 0x52, 0xf8,
	0xd4, 0xb2, 0xf6, 0x6c, 0xc3, 0x3b, 0xdb, 0xe3, 0xe6, 0x3b, 0xf1, 0x9d, 0xfb, 0x3b, 0xf4, 0xbc,
	0x8e, 0xfa, 0xbf, 0x11, 0x34, 0x73, 0xeb, 0x2a, 0xca, 0xe2, 0x84, 0x29, 0x3c, 0x84, 0x83, 0x1b,
	0x19, 0x47, 0x86, 0x8d, 0x8c, 0x62, 0x51, 0x8a, 0x4f, 0x8b, 0x66, 0x65, 0xf9, 0xbf, 0xbd, 0x2d,
	0x9c, 0x20, 0x3c, 0x00, 0x18, 0x19, 0x21, 0xd7, 0x7d, 0xbd, 0x22, 0xfa, 0x20, 0x3e, 0x05, 0x73,
	0xf9, 0xee, 0xfb, 0xf9, 0x94, 0x9b, 0x9f, 0xf3, 0x49, 0x40, 0x45, 0xda, 0x5b, 0x07, 0x8b, 0x5f,
	0x39, 0x9b, 0xf6, 0x34, 0x53, 0x0b, 0x4e, 0x59, 0x4f, 0x49, 0x3a, 0x71, 0xec, 0x97, 0x7b, 0xf1,
	0x2f, 0x00, 0x00, 0xff, 0xff, 0xb4, 0xcc, 0x2a, 0xdf, 0xf7, 0x03, 0x00, 0x00,
}
